### PR TITLE
Add new method to set default `magnitude` of Units

### PR DESCRIPTION
**Pull request by Routhleck**
```python
>>> set_default_magnitude('n') # Sets the default magnitude to 'nano' (10e-9)
>>> set_default_magnitude(-9) # Alternatively, use an integer to represent the exponent of 10
>>> set_default_magnitude({'m': -3, 'kg': -9}) # Set the default magnitude for 'metre' to 'milli' and 'kilogram' to 'nano'
>>> set_default_magnitude({'m': 'm', 'kg': 'n'}) # Alternatively, use a string to represent the magnitude
```

More examples at https://github.com/chaoming0625/brainunit/blob/c25506c9ff9c03dc225ba541f8c517b98a7309f3/brainunit/_unit_test.py#L1477-L1570

### CODE REVIEW

**Comment by chaoming0625** [comment]
Sound very great. I am checking now.

**Comment by chaoming0625** [comment]
> Almost all test cases need to be fixed

这么吓人？

**Comment by Routhleck** [comment]
> > Almost all test cases need to be fixed
> 
> 这么吓人？

https://github.com/chaoming0625/brainunit/actions/runs/10250404914/job/28356059580
262 failed, 33 passed, 2 warnings in 43.34s

**Comment by chaoming0625** [comment]
先不管tests，你先改math，改完后我再看，最后再改tests

**Pull request merged**
